monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_input.*UMIK*" }
    ]
    actions = {
      update-props = {
        priority.session = 0
        priority.driver = 0
      }
    }
  }
]
