#!/usr/bin/env python3
"""Split monolith state files into individual files + index files.

Splits:
  docs/project/user-stories.md  -> docs/project/stories/US-NNN.md + stories-index.md
  docs/project/defects.md       -> docs/project/defects/F-NNN.md  + defects-index.md
  docs/project/decisions.md     -> docs/project/decisions/D-NNN.md + decisions-index.md

Idempotent: safe to run multiple times. Overwrites existing output files.
Does NOT modify the source monolith files.
"""

import re
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent / "docs" / "project"


def split_file(source_path, out_dir, header_re, index_path, index_builder,
               preamble_path=None):
    """Generic splitter for any monolith state file.

    Args:
        source_path:   Path to monolith markdown file
        out_dir:       Directory for individual files
        header_re:     Compiled regex matching entry headers (must have 'id' group)
        index_path:    Path for generated index file
        index_builder: Callable(entries) -> str that builds the index markdown
        preamble_path: If set, write pre-first-entry content here

    Returns:
        Number of entries extracted.
    """
    text = source_path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)

    out_dir.mkdir(parents=True, exist_ok=True)

    # Find all entry boundaries
    boundaries = []  # list of (line_index, entry_id, full_header_line)
    for i, line in enumerate(lines):
        m = header_re.match(line)
        if m:
            boundaries.append((i, m.group("id"), line))

    if not boundaries:
        print(f"  WARNING: no entries found in {source_path.name}")
        return 0

    # Write preamble (everything before first entry) if requested
    if preamble_path is not None:
        preamble_end = boundaries[0][0]
        # Strip trailing blank lines and --- separators from preamble
        preamble_lines = lines[:preamble_end]
        while preamble_lines and preamble_lines[-1].strip() in ("", "---"):
            preamble_lines.pop()
        preamble_lines.append("\n")
        preamble_path.write_text("".join(preamble_lines), encoding="utf-8")

    # Extract each entry
    entries = []  # list of (id, header_line, content_str)
    for idx, (start, entry_id, header_line) in enumerate(boundaries):
        if idx + 1 < len(boundaries):
            end = boundaries[idx + 1][0]
        else:
            end = len(lines)

        # Get entry lines, strip trailing blank lines and --- separators
        entry_lines = lines[start:end]
        while entry_lines and entry_lines[-1].strip() in ("", "---"):
            entry_lines.pop()
        entry_lines.append("\n")

        content = "".join(entry_lines)
        entries.append((entry_id, header_line, content))

        # Write individual file
        out_file = out_dir / f"{entry_id}.md"
        out_file.write_text(content, encoding="utf-8")

    # Write index
    index_content = index_builder(entries)
    index_path.write_text(index_content, encoding="utf-8")

    return len(entries)


# --- Index builders ---

def extract_field(content, field_name):
    """Extract a **Field:** value from markdown content."""
    pattern = rf"\*\*{re.escape(field_name)}:\*\*\s*(.+)"
    m = re.search(pattern, content)
    return m.group(1).strip() if m else ""


def build_stories_index(entries):
    """Build stories-index.md from extracted story entries."""
    lines = [
        "# User Stories Index\n",
        "\n",
        "Auto-generated by `scripts/split-monoliths.py`. Do not edit manually.\n",
        "\n",
        "| ID | Status | Summary |\n",
        "|----|--------|--------|\n",
    ]
    for entry_id, header_line, content in entries:
        # Summary from header: ## US-NNN: Title  or  ## US-NNNa: Title
        m = re.match(r"## \S+:\s*(.+)", header_line)
        summary = m.group(1).strip() if m else ""

        status = extract_field(content, "Status")
        # Truncate long status lines
        if len(status) > 60:
            status = status[:57] + "..."

        lines.append(f"| [{entry_id}](stories/{entry_id}.md) | {status} | {summary} |\n")

    return "".join(lines)


def build_defects_index(entries):
    """Build defects-index.md from extracted defect/enhancement entries."""
    lines = [
        "# Defects Index\n",
        "\n",
        "Auto-generated by `scripts/split-monoliths.py`. Do not edit manually.\n",
        "\n",
        "| ID | Severity | Status | Summary |\n",
        "|----|----------|--------|--------|\n",
    ]
    for entry_id, header_line, content in entries:
        # Summary from header: ## F-NNN: Title (STATUS)
        m = re.match(r"## \S+:\s*(.+)", header_line)
        summary = m.group(1).strip() if m else ""

        # Severity (F-NNN) or Priority (ENH-NNN)
        severity = extract_field(content, "Severity")
        if not severity:
            severity = extract_field(content, "Priority")

        status = extract_field(content, "Status")
        if len(status) > 60:
            status = status[:57] + "..."

        lines.append(f"| [{entry_id}](defects/{entry_id}.md) | {severity} | {status} | {summary} |\n")

    return "".join(lines)


def build_decisions_index(entries):
    """Build decisions-index.md from extracted decision entries."""
    lines = [
        "# Decisions Index\n",
        "\n",
        "Auto-generated by `scripts/split-monoliths.py`. Do not edit manually.\n",
        "\n",
        "| ID | Date | Summary |\n",
        "|----|------|--------|\n",
    ]
    for entry_id, header_line, content in entries:
        # Header format: ## D-NNN: Title (YYYY-MM-DD)
        m = re.match(r"## \S+:\s*(.+)", header_line)
        full_title = m.group(1).strip() if m else ""

        # Extract date from parentheses at end
        dm = re.search(r"\((\d{4}-\d{2}-\d{2})\)\s*$", full_title)
        date = dm.group(1) if dm else ""

        # Summary is title without trailing date
        summary = re.sub(r"\s*\(\d{4}-\d{2}-\d{2}\)\s*$", "", full_title)

        lines.append(f"| [{entry_id}](decisions/{entry_id}.md) | {date} | {summary} |\n")

    return "".join(lines)


# --- Main ---

def main():
    if not PROJECT_DIR.is_dir():
        print(f"ERROR: project directory not found: {PROJECT_DIR}", file=sys.stderr)
        sys.exit(1)

    print(f"Project dir: {PROJECT_DIR}\n")

    # 1. User stories
    stories_src = PROJECT_DIR / "user-stories.md"
    if stories_src.exists():
        print(f"Splitting {stories_src.name}...")
        n = split_file(
            source_path=stories_src,
            out_dir=PROJECT_DIR / "stories",
            header_re=re.compile(r"^## (?P<id>US-\d+[a-z]?):?\s"),
            index_path=PROJECT_DIR / "stories-index.md",
            index_builder=build_stories_index,
            preamble_path=PROJECT_DIR / "dod-gates.md",
        )
        print(f"  -> {n} stories extracted to stories/")
    else:
        print(f"  SKIP: {stories_src} not found")

    # 2. Defects
    defects_src = PROJECT_DIR / "defects.md"
    if defects_src.exists():
        print(f"Splitting {defects_src.name}...")
        n = split_file(
            source_path=defects_src,
            out_dir=PROJECT_DIR / "defects",
            header_re=re.compile(r"^## (?P<id>(?:F|ENH)-\d+):?\s"),
            index_path=PROJECT_DIR / "defects-index.md",
            index_builder=build_defects_index,
            preamble_path=None,
        )
        print(f"  -> {n} defects extracted to defects/")
    else:
        print(f"  SKIP: {defects_src} not found")

    # 3. Decisions
    decisions_src = PROJECT_DIR / "decisions.md"
    if decisions_src.exists():
        print(f"Splitting {decisions_src.name}...")
        n = split_file(
            source_path=decisions_src,
            out_dir=PROJECT_DIR / "decisions",
            header_re=re.compile(r"^## (?P<id>D-\d+):?\s"),
            index_path=PROJECT_DIR / "decisions-index.md",
            index_builder=build_decisions_index,
            preamble_path=None,
        )
        print(f"  -> {n} decisions extracted to decisions/")
    else:
        print(f"  SKIP: {decisions_src} not found")

    print("\nDone.")


if __name__ == "__main__":
    main()
